name: dinov2
channels:
  - defaults
  - pytorch
  - nvidia
  - xformers
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.0.0
  - pytorch-cuda=12.1
  - torchvision
  - omegaconf=2.3.0
  - torchmetrics
  - fvcore
  - pyvips
  - iopath
  - xformers=0.0.18
  - pip
  - pip:
    - git+https://github.com/facebookincubator/submitit
    - --extra-index-url https://pypi.nvidia.com
    - cuml-cu11==24.4.0
    - scikit-learn==1.4.1.post1




